use super::Position;

pub enum Keyword {
    // * Implementing
    Boolean(Position),
    Break(Position),
    Case(Position),
    Const(Position),
    Continue(Position),
    Default(Position),
    Do(Position),
    Else(Position),
    False(Position),
    For(Position),
    Function(Position),
    If(Position),
    In(Position),
    Instanceof(Position),
    Let(Position),
    New(Position),
    Null(Position),
    Return(Position),
    Switch(Position),
    This(Position),
    True(Position),
    Typeof(Position),
    Var(Position),
    While(Position),
    // : Future
    // Await(Position),
    // Catch(Position),
    // Delete(Position),
    // Finally(Position),
    // Throw(Position),
    // Try(Position),
    // : Far Future / Never
    // Abstract(Position),
    // Class(Position),
    // Export(Position),
    // Extends(Position),
    // Final(Position),
    // Goto(Position),
    // Implements(Position),
    // Import(Position),
    // Private(Position),
    // Protected(Position),
    // Public(Position),
    // Static(Position),
    // Super(Position),
    // Void(Position),
}
