use crate::lexer::token::Position;

pub enum Symbol {
    OpenCurlyBracket(Position),
    CloseCurlyBracket(Position),
    OpenParenthesis(Position),
    CloseParenthesis(Position),
    LessThan(Position),
    MoreThan(Position),
    Period(Position),
    Comma(Position),
    Colon(Position),
    SemiColon(Position),
    FatArrow(Position),
    Plus(Position),
    Minus(Position),
    Asterisk(Position),
    Slash(Position),
    Percent(Position),
    Equal(Position),
    NotEqual(Position),
    StrictEqual(Position),
    StrictNotEqual(Position),
    LessThanOrEqual(Position),
    MoreThanOrEqual(Position),
    QuestionMark(Position),
    And(Position),
    Or(Position),
    Not(Position),
}
